version: '3.8'

services:
  c05_mysql:
    image: mysql:8
    container_name: c05_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webcloud
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet

volumes:
  mysql_data:

networks:
  mynet:
    external: true